---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-ponger
  name: ping-ponger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-ponger
  strategy: {}
  template:
    metadata:
      labels:
        app: ping-ponger
    spec:
      containers:
        - image: quay.io/rh-ee-akridl/ping-ponger:1.0
          name: ping-ponger
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ping-ponger
  name: ping-ponger
spec:
  ports:
    - port: 8099
      targetPort: 8099
      protocol: TCP
  selector:
    app: ping-ponger

